# Server configuration
server:
  port: 8070
  contextPath: /shf-dangjian-console #/console

# mybatis配置
mybatis:
  # 配置映射类所在包名
  type-aliases-package : org.gobestsoft.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true #下划线转驼峰

mapper:
    mappers:
        - com.gobestsoft.core.mybatis.MyMapper
    not-empty: false
    identity: POSTGRESQL #MYSQL

pagehelper:
    helperDialect: postgresql #mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


#ueditor 上传文件
web:
  uploadPath: /Users/baylorten/SvnFolder/opt/upload/

spring:
#添加那个目录的文件需要restart
  devtools:
    restart:
      additional-paths: src/main/java

  # 数据库配置
  datasource:
#    driverClassName : com.mysql.jdbc.Driver
#    url : jdbc:mysql://103.24.119.69:43306/gobestdemo?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username : actplus
#    password : actplus
#    driverClassName : com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url : jdbc:sqlserver://103.24.119.69:1433;databaseName=JrbHomePlatformDB
#    username : yf
#    password : yf_2017
#    driverClassName : com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url : jdbc:sqlserver://localhost:1433;databaseName=ShfDemo1
#    username : sa
#    password : sa
    driverClassName : org.postgresql.Driver
    url : jdbc:postgresql://139.196.142.114:5432/gobest_sf_data
    username : postgres
    password : postgres
#    url : jdbc:postgresql://localhost:32771/shfdangjian
#    username : postgres
#    password : postgres

    ###########druid连接池配置#####################
    #指定连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    name : shf-dangjian-console
    # 初始化大小，最小，最大
    initialSize : 10
    minIdle : 5
    maxActive : 200
    removeAbandoned : true
    removeAbandonedTimeout : 1800
    # 配置获取连接等待超时的时间
    maxWait : 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis : 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis : 30000
    validationQuery : select 'x'
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements : true
    maxPoolPreparedStatementPerConnectionSize : 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters : stat,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
#JPA
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    properties:
      hibernate:
#          dialect: org.hibernate.dialect.MySQL5Dialect
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
#配置Redis
  redis:
    # redis数据库索引（默认为0），我们使用索引为1的数据库
    database: 1
    # redis服务器地址（默认为localhost）
    host: localhost
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password:
    # redis连接超时时间（单位为毫秒）
    timeout: 0
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1

########################################################
###THYMELEAF (ThymeleafAutoConfiguration)
########################################################
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.mode=HTML5
#spring.thymeleaf.encoding=UTF-8
# ;charset=<encoding> is added
#spring.thymeleaf.content-type=text/html
# set to false for hot refresh
  thymeleaf:
    cache: false

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.uploadPath}
#    chain:
#      strategy:
#        fixed:
#          enabled: true
#          paths: /static/js/**,/v1.0.0/**
#          version: 1.0.0 
#    chain:
#      strategy:
#        content: 
#          enabled: true
#          paths: /static/**
    
#  freemarker:
     # 模板目录 默认：templates
          
#    template-loader-path: classpath:/freemaker/
#    viewClass: com.gobestsoft.config.MyFreeMarkerView

#spring.datasource.driverClassName = com.mysql.jdbc.Driver
#spring.datasource.url = jdbc:mysql://103.24.119.69:43306/gbwx2?useUnicode=true&characterEncoding=utf-8&useSSL=false
#spring.datasource.username = actplus
#spring.datasource.password = actplus