# Server configuration
server:
  port: 8090
  contextPath: /dahuu #/console



  ########################################################
  ###THYMELEAF (ThymeleafAutoConfiguration)
  ########################################################
  #spring.thymeleaf.prefix=classpath:/templates/
  #spring.thymeleaf.suffix=.html
  #spring.thymeleaf.mode=HTML5
  #spring.thymeleaf.encoding=UTF-8
  # ;charset=<encoding> is added
  #spring.thymeleaf.content-type=text/html
  # set to false for hot refresh
  thymeleaf:
    cache: false

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.uploadPath}
      #    chain:
      #      strategy:
      #        fixed:
      #          enabled: true
      #          paths: /static/js/**,/v1.0.0/**
      #          version: 1.0.0
      #    chain:
      #      strategy:
      #        content:
      #          enabled: true
      #          paths: /static/**

    #  freemarker:
    # 模板目录 默认：templates

#    template-loader-path: classpath:/freemaker/
#    viewClass: com.gobestsoft.config.MyFreeMarkerView
